#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs

singularity exec docker://brainlife/mne:1.0.2 python3 main.py


cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	       "name": "ECG projectors",
           "base64": "$(base64 -w 0 out_figs/ecg_projectors.png)"
       },
       {
           "type": "image/png",
	       "name": " Heartbeat artifacts manifest across Magnetometers",
           "base64": "$(base64 -w 0 out_figs/meg.png)"
       },
       {
           "type": "image/png",
	       "name": " Heartbeat artifacts manifest across Gradiometers",
           "base64": "$(base64 -w 0 out_figs/grad.png)"
       },

       {
           "type": "image/png",
	       "name": " Heartbeat artifacts manifest across EEG",
           "base64": "$(base64 -w 0 out_figs/eeg.png)"
       },
       {
           "type": "image/png",
	       "name": "Joint plot of the projectors and their effect on the time-averaged epochs",
           "base64": "$(base64 -w 0 out_figs/joint-plot.png)"
       }
]
}
EOF
